---
language: node_js
node_js:
  - "6.9.1"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - npm i -g npm@5.0.0
  - npm config set spin false
  - npm install -g bower
  - bower --version
  - npm install phantomjs-prebuilt
  - node_modules/phantomjs-prebuilt/bin/phantomjs --version

install:
  - npm install
  - bower install

script:
  - npm test
